// Code generated by Icestudio 0.9.0-1

`default_nettype none

//---- Top entity
module main (
 input [1:0] v4af14e,
 output [1:0] vd8b0db,
 output [0:5] vinit
);
 wire [0:1] w0;
 assign w0 = v4af14e;
 assign vd8b0db = w0;
 assign vinit = 6'b000000;
endmodule

