// Code generated by Icestudio 0.9.0-1

`default_nettype none

//---- Top entity
module main #(
 parameter v66db49 = 343384
) (
 input vclk,
 output vde1004,
 output vf812bc,
 output [0:6] vinit
);
 localparam p3 = v66db49;
 wire w0;
 wire w1;
 wire w2;
 wire [0:19] w4;
 wire w5;
 wire w6;
 assign vf812bc = w0;
 assign vde1004 = w1;
 assign w5 = vclk;
 assign w6 = vclk;
 assign w1 = w0;
 assign w6 = w5;
 v48b0f4 v060b16 (
  .v4642b6(w0),
  .vb5e8cd(w2),
  .v6dda25(w5)
 );
 v76353b v7d5c1e (
  .ve37344(w2),
  .vb2cfec(w4),
  .v6dda25(w6)
 );
 v95d0ae #(
  .vc5c8ea(p3)
 ) v39701d (
  .v2531bd(w4)
 );
 assign vinit = 7'b0000000;
endmodule

//---- Top entity
module v48b0f4 #(
 parameter v8bcde4 = 0
) (
 input v6dda25,
 input vb5e8cd,
 output v4642b6
);
 localparam p2 = v8bcde4;
 wire w0;
 wire w1;
 wire w3;
 wire w4;
 wire w5;
 assign v4642b6 = w1;
 assign w3 = v6dda25;
 assign w5 = vb5e8cd;
 assign w1 = w0;
 v3676a0 v14ac37 (
  .v0e28cb(w0),
  .vcbab45(w4)
 );
 v883a64 #(
  .v5462c0(p2)
 ) v11582e (
  .v4642b6(w0),
  .ve4a668(w3),
  .v27dec4(w4),
  .vd793aa(w5)
 );
endmodule

//---------------------------------------------------
//-- TFF
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- System TFF with toggle input: It toogles on every system cycle if the input is active
//---------------------------------------------------
//---- Top entity
module v3676a0 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v3676a0_vd54ca1 vd54ca1 (
  .a(w0),
  .q(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT gate (Verilog implementation)
//---------------------------------------------------

module v3676a0_vd54ca1 (
 input a,
 output q
);
 //-- NOT Gate
 assign q = ~a;
 
 
endmodule
//---- Top entity
module v883a64 #(
 parameter v5462c0 = 0
) (
 input ve4a668,
 input v27dec4,
 input vd793aa,
 output v4642b6
);
 localparam p1 = v5462c0;
 wire w0;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w2 = ve4a668;
 assign w3 = v27dec4;
 assign v4642b6 = w5;
 assign w6 = vd793aa;
 assign w5 = w4;
 va40d2f v9ff767 (
  .v030ad0(w0),
  .vb192d0(w3),
  .v27dec4(w4),
  .v2d3366(w6)
 );
 v053dc2 #(
  .v71e305(p1)
 ) v89c757 (
  .vf54559(w0),
  .va4102a(w2),
  .ve8318d(w4)
 );
endmodule

//---------------------------------------------------
//-- 1-bit-reg
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Reg: 1-Bit register
//---------------------------------------------------
//---- Top entity
module va40d2f (
 input v27dec4,
 input vb192d0,
 input v2d3366,
 output v030ad0
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign v030ad0 = w0;
 assign w1 = v2d3366;
 assign w2 = v27dec4;
 assign w3 = vb192d0;
 vd0c4e5 v0f3fef (
  .v030ad0(w0),
  .v2d3366(w1),
  .vb192d0(w2),
  .v27dec4(w3)
 );
endmodule

//---------------------------------------------------
//-- MuxF-2-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 2-to-1 Multplexer (1-bit channels). Fippled version
//---------------------------------------------------
//---- Top entity
module vd0c4e5 (
 input v27dec4,
 input vb192d0,
 input v2d3366,
 output v030ad0
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign v030ad0 = w0;
 assign w2 = v2d3366;
 assign w3 = v2d3366;
 assign w6 = v27dec4;
 assign w7 = vb192d0;
 assign w3 = w2;
 v873425 vaaee1f (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w4)
 );
 vba518e v569873 (
  .vcbab45(w1),
  .v3ca442(w2),
  .v0e28cb(w6)
 );
 v3676a0 v1f00ae (
  .v0e28cb(w3),
  .vcbab45(w5)
 );
 vba518e vc8527f (
  .vcbab45(w4),
  .v3ca442(w5),
  .v0e28cb(w7)
 );
endmodule

//---------------------------------------------------
//-- Mux-2-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 2-to-1 Multplexer (1-bit channels)
//---------------------------------------------------
//---- Top entity
module v873425 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v873425_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR2: Two bits input OR gate
//---------------------------------------------------

module v873425_vf4938a (
 input a,
 input b,
 output c
);
 //-- OR Gate
 //-- Verilog implementation
 
 assign c = a | b;
 
 
endmodule
//---- Top entity
module vba518e (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vba518e_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- AND2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Two bits input And gate
//---------------------------------------------------

module vba518e_vf4938a (
 input a,
 input b,
 output c
);
 //-- AND gate
 //-- Verilog implementation
 
 assign c = a & b;
 
endmodule
//---- Top entity
module v053dc2 #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v053dc2_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- DFF
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- D Flip-flop (verilog implementation)
//---------------------------------------------------

module v053dc2_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg q = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   q <= d;
endmodule
//---- Top entity
module v76353b (
 input v6dda25,
 input [19:0] vb2cfec,
 output [19:0] vb319d4,
 output ve37344
);
 wire [0:19] w0;
 wire w1;
 wire [0:19] w2;
 wire [0:19] w3;
 wire w4;
 wire w5;
 assign w1 = v6dda25;
 assign vb319d4 = w2;
 assign w3 = vb2cfec;
 assign ve37344 = w4;
 assign w2 = w0;
 assign w5 = w4;
 v2d3c65 v55c934 (
  .v545b15(w0),
  .v6dda25(w1),
  .ve556f1(w5)
 );
 vb9ddd5 v90643f (
  .v07eb94(w0),
  .vdb40a4(w3),
  .v4642b6(w4)
 );
endmodule

//---------------------------------------------------
//-- syscounter-M-20bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- syscounter-M-20-bits: 2-bits Module M Syscounter
//---------------------------------------------------
//---- Top entity
module v2d3c65 (
 input v6dda25,
 input ve556f1,
 output [19:0] v545b15,
 output ve37344
);
 wire w0;
 wire [0:19] w1;
 wire [0:19] w2;
 wire w3;
 wire [0:19] w4;
 wire w5;
 assign w0 = ve556f1;
 assign w3 = v6dda25;
 assign v545b15 = w4;
 assign ve37344 = w5;
 assign w4 = w1;
 v8c6884 vfba29e (
  .v782748(w0),
  .v1be022(w1),
  .vf06540(w2),
  .v6dda25(w3)
 );
 vd98b4e v91c0a7 (
  .v4ad898(w1),
  .vd1d627(w2),
  .v4642b6(w5)
 );
endmodule

//---------------------------------------------------
//-- syscounter-rst-16bits CLONE
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 16-bits Syscounter with reset
//---------------------------------------------------
//---- Top entity
module v8c6884 (
 input v6dda25,
 input v782748,
 input [19:0] vf06540,
 output [19:0] v1be022
);
 wire [0:19] w0;
 wire [0:15] w1;
 wire [0:3] w2;
 wire [0:19] w3;
 wire [0:3] w4;
 wire [0:15] w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 assign w0 = vf06540;
 assign v1be022 = w3;
 assign w6 = v6dda25;
 assign w7 = v6dda25;
 assign w8 = v782748;
 assign w9 = v782748;
 assign w7 = w6;
 assign w9 = w8;
 v5c75f6 v9f7443 (
  .v4de61b(w2),
  .v50034e(w4),
  .v6dda25(w6),
  .v782748(w8)
 );
 vafdfd8 vae4b72 (
  .v0bc190(w0),
  .vb68a0b(w1),
  .vd8e8a3(w2)
 );
 vbc711b v5796e0 (
  .vc320da(w1),
  .v3f90b8(w5),
  .v6dda25(w7),
  .v782748(w9)
 );
 vdecca3 v0ddafc (
  .v2e2bd0(w3),
  .v55cd06(w4),
  .vbf8961(w5)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x20
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x20: 20 D flip-flops in paralell with reset
//---------------------------------------------------
//---- Top entity
module v5c75f6 (
 input v6dda25,
 input v782748,
 input [3:0] v4de61b,
 output [3:0] v50034e
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign w6 = v4de61b;
 assign v50034e = w7;
 assign w10 = v6dda25;
 assign w11 = v6dda25;
 assign w12 = v6dda25;
 assign w13 = v6dda25;
 assign w14 = v782748;
 assign w15 = v782748;
 assign w16 = v782748;
 assign w17 = v782748;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w15 = w14;
 assign w16 = w14;
 assign w16 = w15;
 assign w17 = w14;
 assign w17 = w15;
 assign w17 = w16;
 vc4f23a v4b1225 (
  .v3f8943(w2),
  .v64d863(w3),
  .vda577d(w4),
  .v985fcb(w6),
  .v4f1fd3(w8)
 );
 v84f0a1 v6491fd (
  .v03aaf0(w0),
  .vee8a83(w1),
  .vf8041d(w5),
  .v11bca5(w7),
  .vd84a57(w9)
 );
 v2be0f8 v10a04f (
  .v4642b6(w0),
  .vf354ee(w3),
  .vd53b77(w13),
  .v27dec4(w17)
 );
 v2be0f8 v7d9648 (
  .v4642b6(w1),
  .vf354ee(w2),
  .vd53b77(w12),
  .v27dec4(w16)
 );
 v2be0f8 v004b14 (
  .vf354ee(w4),
  .v4642b6(w5),
  .vd53b77(w11),
  .v27dec4(w15)
 );
 v2be0f8 v8aa818 (
  .vf354ee(w8),
  .v4642b6(w9),
  .vd53b77(w10),
  .v27dec4(w14)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x04
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x04: Three D flip-flops in paralell with reset
//---------------------------------------------------
//---- Top entity
module vc4f23a (
 input [3:0] v985fcb,
 output v4f1fd3,
 output vda577d,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign vda577d = w2;
 assign v4f1fd3 = w3;
 assign w4 = v985fcb;
 vc4f23a_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .o2(w2),
  .o3(w3),
  .i(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Split-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Split-all: Split the 4-bits bus into its wires
//---------------------------------------------------

module vc4f23a_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v84f0a1 (
 input vd84a57,
 input vf8041d,
 input vee8a83,
 input v03aaf0,
 output [3:0] v11bca5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign w2 = vf8041d;
 assign w3 = vd84a57;
 assign v11bca5 = w4;
 v84f0a1_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .i2(w2),
  .i3(w3),
  .o(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Join-all: Join all the wires into a 4-bits Bus
//---------------------------------------------------

module v84f0a1_v9a2a06 (
 input i3,
 input i2,
 input i1,
 input i0,
 output [3:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule
//---- Top entity
module v2be0f8 #(
 parameter vbd3217 = 0
) (
 input vd53b77,
 input v27dec4,
 input vf354ee,
 output v4642b6
);
 localparam p5 = vbd3217;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w6;
 assign w2 = v27dec4;
 assign w3 = vf354ee;
 assign v4642b6 = w4;
 assign w6 = vd53b77;
 v3676a0 v7539bf (
  .vcbab45(w1),
  .v0e28cb(w2)
 );
 vba518e vfe8158 (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w3)
 );
 v053dc2 #(
  .v71e305(p5)
 ) vd104a4 (
  .vf54559(w0),
  .ve8318d(w4),
  .va4102a(w6)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x01
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x01: D Flip flop with reset input. When rst=1, the DFF is 0
//---------------------------------------------------
//---- Top entity
module vafdfd8 (
 input [19:0] v0bc190,
 output [3:0] vd8e8a3,
 output [15:0] vb68a0b
);
 wire [0:15] w0;
 wire [0:3] w1;
 wire [0:19] w2;
 assign vb68a0b = w0;
 assign vd8e8a3 = w1;
 assign w2 = v0bc190;
 vafdfd8_v9a2a06 v9a2a06 (
  .o0(w0),
  .o1(w1),
  .i(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus20-Split-4-16
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus20-Split-4-16: Split the 20-bits bus into two buses of 4 and 16 wires
//---------------------------------------------------

module vafdfd8_v9a2a06 (
 input [19:0] i,
 output [3:0] o1,
 output [15:0] o0
);
 assign o1 = i[19:16];
 assign o0 = i[15:0];
endmodule
//---- Top entity
module vbc711b (
 input v6dda25,
 input v782748,
 input [15:0] vc320da,
 output [15:0] v3f90b8
);
 wire [0:15] w0;
 wire [0:15] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign w0 = vc320da;
 assign v3f90b8 = w1;
 assign w10 = v6dda25;
 assign w11 = v6dda25;
 assign w12 = v6dda25;
 assign w13 = v6dda25;
 assign w14 = v782748;
 assign w15 = v782748;
 assign w16 = v782748;
 assign w17 = v782748;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w15 = w14;
 assign w16 = w14;
 assign w16 = w15;
 assign w17 = w14;
 assign w17 = w15;
 assign w17 = w16;
 v5c75f6 vbdef88 (
  .v4de61b(w2),
  .v50034e(w6),
  .v6dda25(w13),
  .v782748(w17)
 );
 v5c75f6 v6188f9 (
  .v4de61b(w3),
  .v50034e(w7),
  .v6dda25(w12),
  .v782748(w16)
 );
 v852bc8 vd47660 (
  .v91b9c1(w0),
  .v527ffb(w2),
  .v71a717(w3),
  .v0b337e(w4),
  .vfc89f9(w5)
 );
 v401a28 v3ef916 (
  .v14a530(w1),
  .vcc76e8(w6),
  .vd531e6(w7),
  .v7ef7d6(w8),
  .v1447f2(w9)
 );
 v5c75f6 v9f7443 (
  .v4de61b(w4),
  .v50034e(w8),
  .v6dda25(w11),
  .v782748(w15)
 );
 v5c75f6 vd2d6b6 (
  .v4de61b(w5),
  .v50034e(w9),
  .v6dda25(w10),
  .v782748(w14)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x16
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x16: 16 D flip-flops in paralell with reset
//---------------------------------------------------
//---- Top entity
module v852bc8 (
 input [15:0] v91b9c1,
 output [3:0] vfc89f9,
 output [3:0] v0b337e,
 output [3:0] v71a717,
 output [3:0] v527ffb
);
 wire [0:15] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 assign w0 = v91b9c1;
 assign v527ffb = w1;
 assign v71a717 = w2;
 assign v0b337e = w3;
 assign vfc89f9 = w4;
 v852bc8_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2),
  .o2(w3),
  .o3(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Split-quarter
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Split-quarter: Split the 16-bits bus into four buses of the same size
//---------------------------------------------------

module v852bc8_v9a2a06 (
 input [15:0] i,
 output [3:0] o3,
 output [3:0] o2,
 output [3:0] o1,
 output [3:0] o0
);
 assign o3 = i[15:12];
 assign o2 = i[11:8];
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v401a28 (
 input [3:0] v1447f2,
 input [3:0] v7ef7d6,
 input [3:0] vd531e6,
 input [3:0] vcc76e8,
 output [15:0] v14a530
);
 wire [0:15] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 assign v14a530 = w0;
 assign w1 = vcc76e8;
 assign w2 = vd531e6;
 assign w3 = v7ef7d6;
 assign w4 = v1447f2;
 v401a28_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2),
  .i2(w3),
  .i3(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Join-quarter
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Join-quarter: Join the four same buses into an 16-bits Bus
//---------------------------------------------------

module v401a28_v9a2a06 (
 input [3:0] i3,
 input [3:0] i2,
 input [3:0] i1,
 input [3:0] i0,
 output [15:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule
//---- Top entity
module vdecca3 (
 input [3:0] v55cd06,
 input [15:0] vbf8961,
 output [19:0] v2e2bd0
);
 wire [0:19] w0;
 wire [0:15] w1;
 wire [0:3] w2;
 assign v2e2bd0 = w0;
 assign w1 = vbf8961;
 assign w2 = v55cd06;
 vdecca3_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus20-Join-4-16
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus20-Join-half: Join the two buses into an 20-bits Bus
//---------------------------------------------------

module vdecca3_v9a2a06 (
 input [3:0] i1,
 input [15:0] i0,
 output [19:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vd98b4e #(
 parameter v6c5139 = 1
) (
 input [19:0] v4ad898,
 output v4642b6,
 output [19:0] vd1d627
);
 localparam p1 = v6c5139;
 wire w0;
 wire [0:19] w2;
 wire [0:19] w3;
 assign v4642b6 = w0;
 assign w2 = v4ad898;
 assign vd1d627 = w3;
 vf09b6a #(
  .vd73390(p1)
 ) v13dd2b (
  .v4642b6(w0),
  .vf0a425(w2),
  .va63e91(w3)
 );
endmodule

//---------------------------------------------------
//-- Inc1-20bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Inc1-20bit: Increment a 20-bits number by one
//---------------------------------------------------
//---- Top entity
module vf09b6a #(
 parameter vd73390 = 0
) (
 input [19:0] vf0a425,
 output v4642b6,
 output [19:0] va63e91
);
 localparam p1 = vd73390;
 wire w0;
 wire [0:19] w2;
 wire [0:19] w3;
 wire [0:19] w4;
 assign v4642b6 = w0;
 assign w3 = vf0a425;
 assign va63e91 = w4;
 v4e3dc9 vb19a98 (
  .v4642b6(w0),
  .ve4715b(w2),
  .v4895ee(w3),
  .vd66696(w4)
 );
 v95d0ae #(
  .vc5c8ea(p1)
 ) v1ff9a2 (
  .v2531bd(w2)
 );
endmodule

//---------------------------------------------------
//-- AdderK-16bits CLONE
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderK-16bit: Adder of 16-bit operand and 16-bit constant
//---------------------------------------------------
//---- Top entity
module v4e3dc9 (
 input [19:0] ve4715b,
 input [19:0] v4895ee,
 output v4642b6,
 output [19:0] vd66696
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:11] w3;
 wire [0:19] w4;
 wire [0:19] w5;
 wire [0:11] w6;
 wire w7;
 wire w8;
 wire [0:3] w9;
 wire [0:15] w10;
 wire [0:19] w11;
 wire [0:3] w12;
 wire [0:3] w13;
 wire [0:7] w14;
 wire [0:7] w15;
 wire [0:7] w16;
 wire [0:7] w17;
 assign w4 = v4895ee;
 assign w5 = ve4715b;
 assign v4642b6 = w8;
 assign vd66696 = w11;
 vcb23aa v8e0bba (
  .v4642b6(w0),
  .v62bf25(w2),
  .v39966a(w16),
  .veb2f59(w17)
 );
 vc3c498 v917bbf (
  .vb9cfc3(w0),
  .veeaa8e(w1),
  .v4642b6(w7),
  .v45c6ee(w14),
  .v20212e(w15)
 );
 v8cc49c v03c3e3 (
  .vb334ae(w1),
  .v2b8a97(w2),
  .v14a530(w10)
 );
 v0f6c39 v672b5a (
  .vb09d88(w3),
  .v0bc190(w4),
  .ve1a6e8(w17)
 );
 vc97ea6 v91419d (
  .v1215c2(w3),
  .v51ed6c(w13),
  .vc673c0(w15)
 );
 v0f6c39 vc7e44e (
  .v0bc190(w5),
  .vb09d88(w6),
  .ve1a6e8(w16)
 );
 vc97ea6 vda03c3 (
  .v1215c2(w6),
  .v51ed6c(w12),
  .vc673c0(w14)
 );
 va1ce30 v32065a (
  .vb9cfc3(w7),
  .v4642b6(w8),
  .v817794(w9),
  .v0550b6(w12),
  .v24708e(w13)
 );
 vdecca3 v23cb4f (
  .v55cd06(w9),
  .vbf8961(w10),
  .v2e2bd0(w11)
 );
endmodule

//---------------------------------------------------
//-- Adder-20bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-20bits: Adder of two operands of 20 bits
//---------------------------------------------------
//---- Top entity
module vcb23aa (
 input [7:0] v39966a,
 input [7:0] veb2f59,
 output v4642b6,
 output [7:0] v62bf25
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:7] w4;
 wire w5;
 wire w6;
 wire [0:3] w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire [0:3] w10;
 assign w0 = veb2f59;
 assign w1 = v39966a;
 assign v62bf25 = w4;
 assign v4642b6 = w5;
 v6bdcd9 vd88c66 (
  .vcc8c7c(w0),
  .v651522(w9),
  .v2cc41f(w10)
 );
 v6bdcd9 v26a0bb (
  .vcc8c7c(w1),
  .v651522(w7),
  .v2cc41f(w8)
 );
 v25966b v9ea427 (
  .v817794(w3),
  .v4642b6(w6),
  .v0550b6(w8),
  .v24708e(w10)
 );
 vafb28f vc75346 (
  .v515fe7(w2),
  .v3c88fc(w3),
  .va9ac17(w4)
 );
 va1ce30 v40c17f (
  .v817794(w2),
  .v4642b6(w5),
  .vb9cfc3(w6),
  .v0550b6(w7),
  .v24708e(w9)
 );
endmodule

//---------------------------------------------------
//-- Adder-8bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-8bits: Adder of two operands of 8 bits
//---------------------------------------------------
//---- Top entity
module v6bdcd9 (
 input [7:0] vcc8c7c,
 output [3:0] v651522,
 output [3:0] v2cc41f
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign v651522 = w0;
 assign v2cc41f = w1;
 assign w2 = vcc8c7c;
 v6bdcd9_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus8-Split-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus8-Split-half: Split the 8-bits bus into two buses of the same size
//---------------------------------------------------

module v6bdcd9_v9a2a06 (
 input [7:0] i,
 output [3:0] o1,
 output [3:0] o0
);
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v25966b (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 v1ea21d vdbe125 (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w14),
  .v82de4f(w17)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w12),
  .v82de4f(w16)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w13),
  .vda577d(w16),
  .v3f8943(w17),
  .v64d863(w18)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w11),
  .vda577d(w12),
  .v3f8943(w14),
  .v64d863(w15)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w11),
  .v82de4f(w13)
 );
endmodule

//---------------------------------------------------
//-- Adder-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-4bits: Adder of two operands of 4 bits
//---------------------------------------------------
//---- Top entity
module v1ea21d (
 input v27dec4,
 input v82de4f,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v82de4f;
 assign w1 = v27dec4;
 assign v4642b6 = w3;
 assign v8e8a67 = w4;
 vad119b vb820a1 (
  .v82de4f(w0),
  .v27dec4(w1),
  .v0ef266(w2),
  .v4642b6(w3),
  .v8e8a67(w4)
 );
 vd30ca9 v23ebb6 (
  .v9fb85f(w2)
 );
endmodule

//---------------------------------------------------
//-- Adder-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-1bit: Adder of two operands of 1 bit
//---------------------------------------------------
//---- Top entity
module vad119b (
 input v27dec4,
 input v82de4f,
 input v0ef266,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign v8e8a67 = w1;
 assign v4642b6 = w5;
 assign w6 = v27dec4;
 assign w7 = v27dec4;
 assign w8 = v82de4f;
 assign w9 = v82de4f;
 assign w10 = v0ef266;
 assign w11 = v0ef266;
 assign w2 = w0;
 assign w7 = w6;
 assign w9 = w8;
 assign w11 = w10;
 vd12401 v2e3d9f (
  .vcbab45(w0),
  .v0e28cb(w7),
  .v3ca442(w9)
 );
 vd12401 vb50462 (
  .v0e28cb(w0),
  .vcbab45(w1),
  .v3ca442(w11)
 );
 vba518e v4882f4 (
  .v3ca442(w2),
  .vcbab45(w3),
  .v0e28cb(w10)
 );
 vba518e v8fcf41 (
  .vcbab45(w4),
  .v0e28cb(w6),
  .v3ca442(w8)
 );
 v873425 vc5b8b9 (
  .v3ca442(w3),
  .v0e28cb(w4),
  .vcbab45(w5)
 );
endmodule

//---------------------------------------------------
//-- AdderC-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-1bit: Adder of two operands of 1 bit plus the carry in
//---------------------------------------------------
//---- Top entity
module vd12401 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vd12401_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR gate: two bits input xor gate
//---------------------------------------------------

module vd12401_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
//---- Top entity
module vd30ca9 (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vd30ca9_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-0
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 0
//---------------------------------------------------

module vd30ca9_vb2eccd (
 output q
);
 //-- Constant bit-0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module vafb28f (
 input [3:0] v515fe7,
 input [3:0] v3c88fc,
 output [7:0] va9ac17
);
 wire [0:7] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 assign va9ac17 = w0;
 assign w1 = v515fe7;
 assign w2 = v3c88fc;
 vafb28f_v9a2a06 v9a2a06 (
  .o(w0),
  .i1(w1),
  .i0(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus8-Join-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus8-Join-half: Join the two same halves into an 8-bits Bus
//---------------------------------------------------

module vafb28f_v9a2a06 (
 input [3:0] i1,
 input [3:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module va1ce30 (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 input vb9cfc3,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 assign w11 = vb9cfc3;
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w13),
  .v82de4f(w17)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w14),
  .vda577d(w17),
  .v3f8943(w18),
  .v64d863(w19)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w12),
  .vda577d(w13),
  .v3f8943(w15),
  .v64d863(w16)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w12),
  .v82de4f(w14)
 );
 vad119b v3599be (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v0ef266(w11),
  .v27dec4(w16),
  .v82de4f(w19)
 );
endmodule

//---------------------------------------------------
//-- AdderC-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-4bits: Adder of two operands of 4 bits and Carry in
//---------------------------------------------------
//---- Top entity
module vc3c498 (
 input [7:0] v45c6ee,
 input [7:0] v20212e,
 input vb9cfc3,
 output v4642b6,
 output [7:0] veeaa8e
);
 wire w0;
 wire w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire [0:3] w10;
 wire [0:3] w11;
 assign w1 = vb9cfc3;
 assign w2 = v45c6ee;
 assign w3 = v20212e;
 assign veeaa8e = w4;
 assign v4642b6 = w7;
 v6bdcd9 v8d795a (
  .vcc8c7c(w3),
  .v651522(w10),
  .v2cc41f(w11)
 );
 v6bdcd9 v23dbc5 (
  .vcc8c7c(w2),
  .v651522(w8),
  .v2cc41f(w9)
 );
 vafb28f vef3a58 (
  .va9ac17(w4),
  .v3c88fc(w5),
  .v515fe7(w6)
 );
 va1ce30 v0ff71a (
  .v4642b6(w0),
  .vb9cfc3(w1),
  .v817794(w5),
  .v0550b6(w9),
  .v24708e(w11)
 );
 va1ce30 v12f94f (
  .vb9cfc3(w0),
  .v817794(w6),
  .v4642b6(w7),
  .v0550b6(w8),
  .v24708e(w10)
 );
endmodule

//---------------------------------------------------
//-- AdderC-8bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-8bits: Adder of two operands of 8 bits and Carry in
//---------------------------------------------------
//---- Top entity
module v8cc49c (
 input [7:0] vb334ae,
 input [7:0] v2b8a97,
 output [15:0] v14a530
);
 wire [0:15] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v14a530 = w0;
 assign w1 = v2b8a97;
 assign w2 = vb334ae;
 v8cc49c_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Join-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Join-half: Join the two same halves into an 16-bits Bus
//---------------------------------------------------

module v8cc49c_v9a2a06 (
 input [7:0] i1,
 input [7:0] i0,
 output [15:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v0f6c39 (
 input [19:0] v0bc190,
 output [11:0] vb09d88,
 output [7:0] ve1a6e8
);
 wire [0:19] w0;
 wire [0:7] w1;
 wire [0:11] w2;
 assign w0 = v0bc190;
 assign ve1a6e8 = w1;
 assign vb09d88 = w2;
 v0f6c39_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus20-Split-12-8
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus20-Split-8-12: Split the 20-bits bus into two buses of 8 and 12 wires
//---------------------------------------------------

module v0f6c39_v9a2a06 (
 input [19:0] i,
 output [11:0] o1,
 output [7:0] o0
);
 assign o1 = i[19:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module vc97ea6 (
 input [11:0] v1215c2,
 output [3:0] v51ed6c,
 output [7:0] vc673c0
);
 wire [0:3] w0;
 wire [0:11] w1;
 wire [0:7] w2;
 assign v51ed6c = w0;
 assign w1 = v1215c2;
 assign vc673c0 = w2;
 vc97ea6_v9a2a06 v9a2a06 (
  .o1(w0),
  .i(w1),
  .o0(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus12-Split-4-8
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus12-Split-4-8: Split the 12-bits bus into two buses of 4 and 8 wires
//---------------------------------------------------

module vc97ea6_v9a2a06 (
 input [11:0] i,
 output [3:0] o1,
 output [7:0] o0
);
 
 assign o1 = i[11:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module v95d0ae #(
 parameter vc5c8ea = 0
) (
 output [19:0] v2531bd
);
 localparam p0 = vc5c8ea;
 wire [0:19] w1;
 assign v2531bd = w1;
 v95d0ae_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- 20-bits-gen-constant
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Generic: 20-bits generic constant
//---------------------------------------------------

module v95d0ae_v465065 #(
 parameter VALUE = 0
) (
 output [19:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module vb9ddd5 (
 input [19:0] vdb40a4,
 input [19:0] v07eb94,
 output v4642b6
);
 wire w0;
 wire [0:19] w1;
 wire [0:19] w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:3] w6;
 wire [0:7] w7;
 wire [0:7] w8;
 wire [0:3] w9;
 wire [0:7] w10;
 wire [0:7] w11;
 assign v4642b6 = w0;
 assign w1 = v07eb94;
 assign w2 = vdb40a4;
 vb2762a vb6832a (
  .v4642b6(w3),
  .v715730(w8),
  .vf191e6(w11)
 );
 vb2762a v302658 (
  .v4642b6(w4),
  .v715730(w7),
  .vf191e6(w10)
 );
 v2dbbdf vb63230 (
  .v0bc190(w1),
  .v906d8f(w9),
  .v89b162(w10),
  .ve1a6e8(w11)
 );
 v2dbbdf veb4dc0 (
  .v0bc190(w2),
  .v906d8f(w6),
  .v89b162(w7),
  .ve1a6e8(w8)
 );
 v438230 vc72070 (
  .v4642b6(w5),
  .v693354(w6),
  .v5369cd(w9)
 );
 vae245c v9196c7 (
  .vcbab45(w0),
  .v3ca442(w3),
  .v0e28cb(w4),
  .v033bf6(w5)
 );
endmodule

//---------------------------------------------------
//-- comp2-20bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comp2-20bit: Comparator of two 20-bit numbers
//---------------------------------------------------
//---- Top entity
module vb2762a (
 input [7:0] v715730,
 input [7:0] vf191e6,
 output v4642b6
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire [0:3] w8;
 assign v4642b6 = w0;
 assign w3 = v715730;
 assign w4 = vf191e6;
 v438230 v577a36 (
  .v4642b6(w2),
  .v693354(w6),
  .v5369cd(w8)
 );
 vba518e v707c6e (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w2)
 );
 v6bdcd9 v921a9f (
  .vcc8c7c(w4),
  .v651522(w7),
  .v2cc41f(w8)
 );
 v6bdcd9 v8cfa4d (
  .vcc8c7c(w3),
  .v651522(w5),
  .v2cc41f(w6)
 );
 v438230 vfc1765 (
  .v4642b6(w1),
  .v693354(w5),
  .v5369cd(w7)
 );
endmodule

//---------------------------------------------------
//-- comp2-8bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comp2-8bit: Comparator of two 8-bit numbers
//---------------------------------------------------
//---- Top entity
module v438230 (
 input [3:0] v693354,
 input [3:0] v5369cd,
 output v4642b6
);
 wire w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 assign v4642b6 = w0;
 assign w1 = v693354;
 assign w2 = v5369cd;
 v23b15b v09a5a5 (
  .v4642b6(w3),
  .v27dec4(w12),
  .v6848e9(w14)
 );
 v23b15b vc1b29d (
  .v4642b6(w4),
  .v27dec4(w11),
  .v6848e9(w13)
 );
 v23b15b vcd27ce (
  .v4642b6(w5),
  .v27dec4(w9),
  .v6848e9(w10)
 );
 vc4f23a vea9c80 (
  .v985fcb(w1),
  .v4f1fd3(w7),
  .vda577d(w9),
  .v3f8943(w11),
  .v64d863(w12)
 );
 vc4f23a va7dcdc (
  .v985fcb(w2),
  .v4f1fd3(w8),
  .vda577d(w10),
  .v3f8943(w13),
  .v64d863(w14)
 );
 v23b15b va0849c (
  .v4642b6(w6),
  .v27dec4(w7),
  .v6848e9(w8)
 );
 veffd42 v6e3e65 (
  .vcbab45(w0),
  .v3ca442(w3),
  .v0e28cb(w4),
  .v033bf6(w5),
  .v9eb652(w6)
 );
endmodule

//---------------------------------------------------
//-- comp2-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comp2-4bit: Comparator of two 4-bit numbers
//---------------------------------------------------
//---- Top entity
module v23b15b (
 input v27dec4,
 input v6848e9,
 output v4642b6
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w1 = v27dec4;
 assign v4642b6 = w2;
 assign w3 = v6848e9;
 vd12401 v955b2b (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w3)
 );
 v3676a0 vf92936 (
  .v0e28cb(w0),
  .vcbab45(w2)
 );
endmodule

//---------------------------------------------------
//-- comp2-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comp2-1bit: Comparator of two 1-bit numbers
//---------------------------------------------------
//---- Top entity
module veffd42 (
 input v9eb652,
 input v033bf6,
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w0 = v3ca442;
 assign w1 = v9eb652;
 assign w2 = v033bf6;
 assign w3 = v0e28cb;
 assign vcbab45 = w4;
 vba518e vf3ef0f (
  .v3ca442(w0),
  .v0e28cb(w3),
  .vcbab45(w6)
 );
 vba518e vdcc53d (
  .v0e28cb(w1),
  .v3ca442(w2),
  .vcbab45(w5)
 );
 vba518e v17ac22 (
  .vcbab45(w4),
  .v0e28cb(w5),
  .v3ca442(w6)
 );
endmodule

//---------------------------------------------------
//-- AND4
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Three bits input And gate
//---------------------------------------------------
//---- Top entity
module v2dbbdf (
 input [19:0] v0bc190,
 output [3:0] v906d8f,
 output [7:0] v89b162,
 output [7:0] ve1a6e8
);
 wire [0:19] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:3] w3;
 assign w0 = v0bc190;
 assign ve1a6e8 = w1;
 assign v89b162 = w2;
 assign v906d8f = w3;
 v2dbbdf_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2),
  .o2(w3)
 );
endmodule

//---------------------------------------------------
//-- Bus20-Split-4-8-8
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus20-Split-4-8-8: Split the 20-bits bus into three buses of 4, 8 and 8 wires
//---------------------------------------------------

module v2dbbdf_v9a2a06 (
 input [19:0] i,
 output [3:0] o2,
 output [7:0] o1,
 output [7:0] o0
);
 assign o2 = i[19:16];
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module vae245c (
 input v033bf6,
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v033bf6;
 assign w1 = v0e28cb;
 assign w2 = v3ca442;
 assign vcbab45 = w4;
 vba518e v19b5b0 (
  .v0e28cb(w0),
  .v3ca442(w1),
  .vcbab45(w3)
 );
 vba518e vf3ef0f (
  .v3ca442(w2),
  .v0e28cb(w3),
  .vcbab45(w4)
 );
endmodule

//---------------------------------------------------
//-- AND3
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Three bits input And gate
//---------------------------------------------------
